config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#home'
  get 'home', to: 'welcome#home'
  get 'directory', to: 'welcome#directory'
  get 'rates', to: 'welcome#rates'
  get 'partner', to: 'welcome#partner'
  get 'buy', to: 'welcome#buy'
  get 'receipt', to: 'welcome#receipt'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def directory
  end
  
  def rates
  end
  
  def partner
  end
  
  def buy
  end
  
  def receipt
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MicroWhales</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/buy.html.erb
<header>
  <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
 <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">﻿
</header>

<style>
  ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}
li {
    float: left;
}
li a, .dropbtn {
    display: inline-block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}
li a:hover, .dropdown:hover .dropbtn {
    background-color: red;
}
</style>

<div class="pageOne text-center" id="p1">
  <ul class="nav nav-pills">
    <div>
      <li> <%= link_to 'Home', home_path %></li>
    </div>
    <div>
      <li><%= link_to 'Rates', rates_path %></li>
    </div>
    <div>
      <li><%= link_to 'Partner', partner_path %></li>
    </div>
  </ul>  

    <center>
  <div class="block text-center">
  <h1>Micro Whales
</h1>
  <h2>Gaming Currency</h2> 
    </center>
<form class="form-horizontal">
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">User Name</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="inputEmail3" placeholder="User Name">
    </div>
  </div>
  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Email Address</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="inputPassword3" placeholder="Email Address">
    </div>
  </div>
      <div class="form-group">
     <label for="inputPassword3" class="col-sm-2 control-label">Phone Number</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="inputPassword3" placeholder="Phone Number">
    </div>
  </div>
      <div class="form-group">
   <label for="inputPassword3" class="col-sm-2 control-label">Amount to buy</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="inputPassword3" placeholder="Amount to buy">
    </div>
  </div>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default"><%= link_to "Submit", receipt_path %></button>
    </div>
  </div>
</form>

app/views/welcome/directory.html.erb
<header>
  <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
 <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">﻿
</header>
<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}
  li {
    float: left;
}
li a, .dropbtn {
    display: inline-block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}
li a:hover, .dropdown:hover .dropbtn {
    background-color: red;
}
  .lii{
    display: inline-block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
  }
</style>
<div class="pageOne text-center" id="p1">
<ul class="nav nav-pills">
    <div>
      <li> <%= link_to 'Home', home_path %></li>
    </div>
    <div>
      <li><%= link_to 'Rates', rates_path %></li>
    </div>
    <div>
      <li><%= link_to 'Partner', partner_path %></li>
    </div>
  </ul> 

<div class="block text-center">
  <h1>Micro Whales
</h1>
  <h2>Gaming Currency</h2> 
  
  <center><br/><br/>
    
    <h3>
      Directory
    </h3>
    <p>
      List of Gaming industries
    </p>
    <lii><%= link_to 'Electronic Arts', buy_path %></lii>
  <br/>
    <lii><%= link_to 'Epic Games', buy_path %></lii>
   <br/>
    <lii><%= link_to 'Activism', buy_path %></lii>
   <br/>
    <lii><%= link_to 'Valve', buy_path %></lii>
  </center>
  
  
   
   

app/views/welcome/home.html.erb
<header>
  <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
 <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">﻿
</header>

<style>
   p{
    font-size: 10px;
  }
  h1{
    font-size: 60px;
    color: blue;
  }
  ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}
li {
    float: left;
}
li a, .dropbtn {
    display: inline-block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}
li a:hover, .dropdown:hover .dropbtn {
    background-color: red;
}

</style>
<div class="pageOne text-center" id="p1">
  <ul class="nav nav-pills">
    <div>
      <li> <%= link_to 'Directory', directory_path %></li>
    </div>
    <div>
      <li><%= link_to 'Rates', rates_path %></li>
    </div>
    <div>
      <li><%= link_to 'Partner', partner_path %></li>
    </div>
    <div><object align="right">
       <%= image_tag("MW.jpg", size:"50x50", :alt => "MW") %>
      </object> 
    </div>
  </ul>

  <center>
  <div class="block text-center">
  <h1>Micro Whales
</h1>
  <h2><i>In-Game-Currency Micro-Transaction Intermediary</i></h2> 
    
   <%= image_tag("microwhales1.jpg", :alt => "micro whales") %>
  
    <div class="btnList text-center">

    <a class="btn btn-default" href="#"><i class="fa fa-comment-o" aria-hidden="true"></i>
    FAQ</a>
      <a class="btn btn-default" href="#"><i class="fa fa-address-book" aria-hidden="true"></i>
    Contact</a>
      </div>
    <br/>
     <p>	Copyright © Micro Whales. All Rights Reserved</p>
  </div>
</div>
  </center>

app/views/welcome/partner.html.erb
<header>
  <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
 <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">﻿
</header>

<style>
  ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}
li {
    float: left;
}
li a, .dropbtn {
    display: inline-block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}
li a:hover, .dropdown:hover .dropbtn {
    background-color: red;
}
</style>

<div class="pageOne text-center" id="p1">
  <ul class="nav nav-pills">
    <div>
      <li> <%= link_to 'Home', home_path %></li>
    </div>
    <div>
      <li><%= link_to 'Rates', rates_path %></li>
    </div>
    <div>
      <li><%= link_to 'Partner', partner_path %></li>
    </div>
  </ul> 

<div class="block text-center">
  <h1>Micro Whales
</h1>
  <h2>Gaming Currency</h2> 
   
   <p>
     Partner with us now and be apart of Micro Whales
   </p>
   
   <form class="form-horizontal">
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Company Name</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="inputEmail3" placeholder="Company Name">
    </div>
  </div>
  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Address</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="inputPassword3" placeholder="Address">
    </div>
  </div>
      <div class="form-group">
     <label for="inputPassword3" class="col-sm-2 control-label">Contact info</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="inputPassword3" placeholder="Contact Info">
    </div>
  </div>
      <div class="form-group">
   <label for="inputPassword3" class="col-sm-2 control-label">Exchange Rate</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="inputPassword3" placeholder="Exchange Rate">
    </div>
  </div>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Submit</button>
    </div>
  </div>
</form>

     

app/views/welcome/rates.html.erb
<header>
  <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
 <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">﻿
</header>

<style>
  ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}
li {
    float: left;
}
li a, .dropbtn {
    display: inline-block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}
li a:hover, .dropdown:hover .dropbtn {
    background-color: red;
}
</style>

<div class="pageOne text-center" id="p1">
  <ul class="nav nav-pills">
    <div>
      <li> <%= link_to 'Home', home_path %></li>
    </div>
    <div>
      <li><%= link_to 'Rates', rates_path %></li>
    </div>
    <div>
      <li><%= link_to 'Partner', partner_path %></li>
    </div>
  </ul> 

<div class="block text-center">
  <h1>Micro Whales
</h1>
  <h2>Gaming Currency</h2> 

app/views/welcome/receipt.html.erb
<header>
  <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
 <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">﻿
</header>
<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}
  li {
    float: left;
}
li a, .dropbtn {
    display: inline-block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}
li a:hover, .dropdown:hover .dropbtn {
    background-color: red;
}
  .lii{
    display: inline-block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
  }
</style>
<div class="pageOne text-center" id="p1">
<ul class="nav nav-pills">
    <div>
      <li> <%= link_to 'Home', home_path %></li>
    </div>
    <div>
      <li><%= link_to 'Rates', rates_path %></li>
    </div>
    <div>
      <li><%= link_to 'Partner', partner_path %></li>
    </div>
  </ul> 

<div class="block text-center">
  <h1>Micro Whales
</h1>
  <h2>Gaming Currency</h2> <br/><br/>
  <p>
      Confirmation #: 5567782188 <br/>
  Your Transaction was succesfully processed
  You will receive a receipt via email shortly.
  </p>

  
  
  <center><br/><br/>
    
    
    